AWSTemplateFormatVersion: '2010-09-09'
Description: Instância EC2 com Ubuntu e Apache

Parameters:
  KeyName:
    Type: String
    Description: Nome da chave SSH

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0  # Ubuntu 18.04
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso SSH e HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstancePublicIP:
    Description: IP público da instância
    Value: !GetAtt EC2Instance.PublicIp
